package com.sebastiank.obd2.utils;

public enum Unit {
  NO_UNIT,
  PERCENT,
  DEGREE_CELSIUS,
  KILO_PASCAL,
  REVOLUTIONS_PER_MINUTE,
  KILOMETERS_PER_HOUR,
  DEGREE_BEFORE_TDC,
  GRAMS_PER_SECOND,
  VOLTS,
  SECONDS,
  RATIO,
  COUNT,
  KILOMETER,
  PASCAL,
  MILLI_AMPERE,
  DEGREE,
  MINUTES,
  LITER_PER_HOUR,
  NEWTON_METER,
  HOURS,
  KILOGRAM_PER_HOUR,
  PARTS_PER_MILLION,
  MILLI_GRAM_PER_STROKE
}
